name: Web Build-Test

on: [push]

defaults:
  run:
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.8

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npm run build

      - name: Unit test
        run: npm test --coverage

      - name: Lint code
        run: npm run lint
